name: Second Workflow
on: 
  issues:
    type: opened
jobs:
  issue-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Notification message
        runs: echo 'Issue opened ${{ toJSON(github.event.issue) }}'